apply viewSets action failed
Artanic30/East-Star-Chess-Backend pull request #3
Opened 2019-09-10 15:31 UTC by Artanic30

按照studentPlatform 里的 account的url来配置
前段发来的请求  [10/Sep/2019 23:24:08] "GET /api/game/140/init_game/ HTTP/1.1" 200 2110
路由无法匹配

2019-09-10 15:40 UTC, Artanic30 commented
路由可以匹配 /api/game/init_game/
研究下怎么传递参数

2019-09-11 00:42 UTC, alienmao commented
弄成/api/game/init_game/140

然后把action中的detail改成true就行了

2019-09-11 00:49 UTC, harveyqiu requested changes
detail = true

2019-09-11 02:53 UTC, Artanic30 commented
弄好了！

2019-09-11 02:54 UTC, merged

2019-09-11 03:36 UTC, alienmao commented
qltnb

2019-09-11 04:08 UTC, alienmao commented
怎么都不写test的啊
这不是个好习惯